name: labs_week5
version: 0.1.0

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  http: ^1.6.0

flutter:
  uses-material-design: true
