name: week5

environment:
  sdk: 3.9.0
  flutter: 3.35.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  leancode_lint: ^18.0.0

flutter:
  uses-material-design: true
