include: package:leancode_lint/analysis_options.yaml

plugins:
  leancode_lint: ^27.0.0

analyzer:
  exclude:
    - '**.g.dart'
    - '**/build/**'
    - build/**
    - android/**
    - web/**
    - windows/**
    - macos/**
