name: flutter_at_mini

environment:
  sdk: 3.13.4
  flutter: 3.47.5

workspace:
  - labs/*
  - lectures/*
  - lectures/week1/flutter
  - lectures/week3/examples

dev_dependencies:
  leancode_lint: ^27.0.0
