name: week11_lecture
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  bloc: ^8.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
