name: lecture_week5

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  leancode_cubit_utils: ^0.4.2

dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/undraw_dog.png
