name: lecture_week5

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  leancode_cubit_utils: ^0.5.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - images/undraw_dog.png
