name: week7
version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  provider: 6.1.2

dev_dependencies:
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true
