name: week7
version: 1.0.0+1

environment:
  sdk: 3.9.0
  flutter: 3.35.2

dependencies:
  cloud_firestore: ^6.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1

dev_dependencies:
  leancode_lint: ^18.0.0

flutter:
  uses-material-design: true
