name: week7
version: 1.0.0+1

environment:
  sdk: 3.9.2
  flutter: 3.35.5

dependencies:
  cloud_firestore: ^6.0.2
  collection: ^1.19.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1

dev_dependencies:
  leancode_lint: ^19.0.0

flutter:
  uses-material-design: true
