name: labs_week4

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  bookstore_data:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  intl: ^0.20.2
  provider: ^6.1.5+1

flutter:
  uses-material-design: true
