name: week3

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  bookstore_data:
    path: packages/bookstore_data
  flutter:
    sdk: flutter
  go_router: ^14.3.0

dev_dependencies:
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true
