name: labs_week3

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  bookstore_data: ^0.0.0
  flutter:
    sdk: flutter
  go_router: ^18.0.2
  intl: ^0.20.3

flutter:
  uses-material-design: true
