// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--YuczORgmXyAK5jswAmcJZpEWKXxLw8',
    appId: '1:719560878252:web:ba3e00c150cca035165709',
    messagingSenderId: '719560878252',
    projectId: 'flutter-at-mini-2024-lab-7',
    authDomain: 'flutter-at-mini-2024-lab-7.firebaseapp.com',
    storageBucket: 'flutter-at-mini-2024-lab-7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV899mwZZRZP-Fly7OhI7d0f9Yisltbqo',
    appId: '1:719560878252:ios:17dfb18439244295165709',
    messagingSenderId: '719560878252',
    projectId: 'flutter-at-mini-2024-lab-7',
    storageBucket: 'flutter-at-mini-2024-lab-7.firebasestorage.app',
    iosBundleId: 'com.example.week7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA--YuczORgmXyAK5jswAmcJZpEWKXxLw8',
    appId: '1:719560878252:web:071f92c7f8f864e6165709',
    messagingSenderId: '719560878252',
    projectId: 'flutter-at-mini-2024-lab-7',
    authDomain: 'flutter-at-mini-2024-lab-7.firebaseapp.com',
    storageBucket: 'flutter-at-mini-2024-lab-7.firebasestorage.app',
  );
}
