name: lecture_week2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.13.5
  flutter: 3.47.6

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
