name: week6

environment:
  sdk: 3.9.2
  flutter: 3.35.5

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.5.0

dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter
  leancode_lint: ^18.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/undraw_dog.png
