name: week6

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2

dev_dependencies:
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true

  assets:
    - images/undraw_dog.png
