// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtg-VANaxt5OWI1aVWmhCAGW_2xWsoEcU',
    appId: '1:647495204529:web:fa7e1cbaffa3f902a0ec90',
    messagingSenderId: '647495204529',
    projectId: 'water-4a614',
    authDomain: 'water-4a614.firebaseapp.com',
    storageBucket: 'water-4a614.appspot.com',
    measurementId: 'G-N9CWVERRYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPTojAsUDclqo31Km2-62B_rB0cleZDc',
    appId: '1:647495204529:android:cae9652cb3775181a0ec90',
    messagingSenderId: '647495204529',
    projectId: 'water-4a614',
    storageBucket: 'water-4a614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPDFCdjMFFBUAHCOZPR9TQjgCcjXZCd8',
    appId: '1:647495204529:ios:6b3fa9f3621052bda0ec90',
    messagingSenderId: '647495204529',
    projectId: 'water-4a614',
    storageBucket: 'water-4a614.appspot.com',
    iosClientId:
        '647495204529-nse2i1fdt88sh338lab1tf95m0hti9sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7Lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPDFCdjMFFBUAHCOZPR9TQjgCcjXZCd8',
    appId: '1:647495204529:ios:6b3fa9f3621052bda0ec90',
    messagingSenderId: '647495204529',
    projectId: 'water-4a614',
    storageBucket: 'water-4a614.appspot.com',
    iosClientId:
        '647495204529-nse2i1fdt88sh338lab1tf95m0hti9sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7Lab',
  );
}
