name: testing
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  json_annotation: 4.7.0
  http: 0.13.5
  provider: 6.0.4

dev_dependencies:
  bloc_test: 9.1.0
  build_runner: 2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: 0.3.0
  golden_toolkit: 0.13.0
  json_serializable: 6.5.4

flutter:
  uses-material-design: true
