name: forms_lecture
description: Examples to the flutter forms lecture
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  form_bloc: ^0.30.0
  freezed_annotation: 2.2.0
  meta: ^1.8.0
  provider: ^6.0.4
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.3.2
  freezed: 2.3.0

flutter:
  uses-material-design: true
