name: forms_lecture
description: Examples to the flutter forms lecture
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  form_bloc: ^0.31.0
  freezed_annotation: ^2.4.1
  meta: ^1.9.1
  provider: ^6.0.5
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true
