// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdb5Iq6lC4eu0QxS3Ggzoi3JZRCUFia0k',
    appId: '1:152105901480:web:7d2206ffd4bdf18b80519d',
    messagingSenderId: '152105901480',
    projectId: 'shoutbox-dd69b',
    authDomain: 'shoutbox-dd69b.firebaseapp.com',
    storageBucket: 'shoutbox-dd69b.appspot.com',
    measurementId: 'G-9NZWMWTGC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIr6ijLyezUfFjCF0CKV2x2MBcBYGYX2c',
    appId: '1:152105901480:android:1e1cb93a53679cfb80519d',
    messagingSenderId: '152105901480',
    projectId: 'shoutbox-dd69b',
    storageBucket: 'shoutbox-dd69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKFd_AjAy0lLzIS5IvLpmt2qilfzy65Y',
    appId: '1:152105901480:ios:1bd1b1015ee4d8f280519d',
    messagingSenderId: '152105901480',
    projectId: 'shoutbox-dd69b',
    storageBucket: 'shoutbox-dd69b.appspot.com',
    iosClientId: '152105901480-h2cjeferveh10nfkgjgo7f9k9s1kii45.apps.googleusercontent.com',
    iosBundleId: 'com.example.week6Lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKFd_AjAy0lLzIS5IvLpmt2qilfzy65Y',
    appId: '1:152105901480:ios:1bd1b1015ee4d8f280519d',
    messagingSenderId: '152105901480',
    projectId: 'shoutbox-dd69b',
    storageBucket: 'shoutbox-dd69b.appspot.com',
    iosClientId: '152105901480-h2cjeferveh10nfkgjgo7f9k9s1kii45.apps.googleusercontent.com',
    iosBundleId: 'com.example.week6Lab',
  );
}
